fint:
  org-id: fintlabs.no
  cache:
    defaultCacheEntryTimeToLiveMillis: 20000
    defaultCacheHeapSize: 10000
  kafka:
    default-replicas: 1
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${fint.application-id}
    topic:
      #org-id: ${fint.org-id}
      org-id: fintlabs-no
      domain-context: kontroll
    application-id: fint-kontroll-device-catalog
spring:
  application:
    name: fint-kontroll-device-catalog
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      schema: device
  kafka:
    consumer:
      group-id: fint-kontroll-device-catalog
    #bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: device

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8182
logging:
  level:
    root: INFO
    org.apache.kafka.clients: WARN
    org.apache.kafka.common: WARN
    org.apache.kafka.clients.consumer: WARN
    org.apache.kafka.clients.producer: WARN
    org.springframework.kafka: WARN
    no.fintlabs.kafka: WARN
