fint:
  org-id: fintlabs.no
spring:
  application:
    name: fint-kontroll-device-catalog
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      schema: device

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: device

  flyway:
    enabled: true
    locations: classpath:db/migration
#    default-schema: bildebank
#    schemas: bildebank
#    baseline-on-migrate: true
#    baseline-version: 1
server:
  port: 8182