fint:
  org-id: fintlabs.no
  application-id: fint-kontroll-device-catalog
  cache:
    defaultCacheEntryTimeToLiveMillis: 20000
    defaultCacheHeapSize: 10000
  kontroll:
    publishing:
      initial-delay: 100000
      fixed-delay: 300000

spring:
  application:
    name: fint-kontroll-device-catalog
  kafka:
    consumer:
      group-id: fint-kontroll-device-catalog
  flyway:
    enabled: true
    locations: classpath:db/migration
  profiles:
    include:
      - kafka
      - db
      - observability
logging:
  level:
    root: INFO
    org.apache.kafka.clients: WARN
    org.apache.kafka.common: WARN
    org.apache.kafka.clients.consumer: WARN
    org.apache.kafka.clients.producer: WARN
    org.springframework.kafka: WARN
    no.fintlabs.kafka: WARN
    no.fintlabs.cache.ehcache.FintEhCacheEventLogger: WARN

